version: "3.8"

services:
  wake-on-lan:
    build: .
    network_mode: "host"
    container_name: wake-on-lan
    restart: unless-stopped
    environment:
      - FLASK_APP=wake_on_lan.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=8081
    volumes:
      - ./app:/app
