version: "3.8"
services:
  wake-on-lan:
    build: .
    ports:
      - "8080:8080"
    container_name: wake-on-lan
    restart: unless-stopped
    network_mode: "host"
    environment:
      - FLASK_APP=wake_on_lan.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=8080
    volumes:
      - ./app:/app
